apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-xray
  labels:
    metrics: jfrog
spec:
  selector:
    matchLabels:
      app: xray
  endpoints:
  - port: metrics
    interval: 10s