apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-artifactory-ha-member
  labels:
    metrics: jfrog
spec:
  selector:
    matchLabels:
      app: artifactory-ha-member
  endpoints:
  - port: metrics
    interval: 15s