apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: splunk
  name: splunk
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splunk
  template:
    metadata:
      labels:
        app: splunk
    spec:
      containers:
        - image: splunk/splunk:latest
          imagePullPolicy: "Always"
          name: splunk
          env:
            - name: SPLUNK_START_ARGS
              value: "--accept-license"
            - name: SPLUNK_PASSWORD
              value: "password1"
          ports:
            -  containerPort: 8000
            -  containerPort: 8088
            -  containerPort: 8089   
---
kind: Service
apiVersion: v1
metadata:
  name: splunk
  labels:
    app: splunk
spec:
  selector:
    app: splunk
  ports:
  - name: web
    protocol: TCP
    port: 8000
    targetPort: 8000
  - name: hec
    protocol: TCP
    port: 8088
    targetPort: 8088
  - name: api
    protocol: TCP
    port: 8089
    targetPort: 8089
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: splunk-lb
  labels:
    app: splunk
spec:
  selector:
    app: splunk
  ports:
  - name: http 
    protocol: TCP
    port: 80
    targetPort: 8000
  - name: hec
    protocol: TCP
    port: 8088
    targetPort: 8088
  - name: api
    protocol: TCP
    port: 8089
    targetPort: 8089
  type: LoadBalancer
